// Generated by scripts/generate-image-assets.mjs — do not edit by hand.
export type CompareImageMeta = { width: number; height: number }

export const compareImageMeta: Record<string, CompareImageMeta> = {
	'/compare/cat-orig.png': { width: 1200, height: 1600 },
	'/compare/cat.JPG': { width: 1200, height: 1600 },
	'/compare/dom-orig.png': { width: 1200, height: 900 },
	'/compare/dom.JPG': { width: 1200, height: 900 },
	'/compare/koleso-orig.png': { width: 1200, height: 1600 },
	'/compare/koleso.JPG': { width: 1200, height: 1600 }
}
