// Generated by scripts/generate-compare-blur.mjs — do not edit by hand.
export type CompareImageMeta = { width: number; height: number }

export const compareImageMeta: Record<string, CompareImageMeta> = {
	'/compare/cat-orig.png': { width: 3024, height: 4032 },
	'/compare/cat.JPG': { width: 3024, height: 4032 },
	'/compare/dom-orig.png': { width: 4032, height: 3024 },
	'/compare/dom.JPG': { width: 4032, height: 3024 },
	'/compare/koleso-orig.png': { width: 1422, height: 1896 },
	'/compare/koleso.JPG': { width: 3024, height: 4032 }
}
